<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\THMS.Data\THMS.Data.csproj" />
    <ProjectReference Include="..\THMS.Domain\THMS.Domain.csproj" />
  </ItemGroup>

</Project>
