<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>THMS.Logic.ViewModels</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Energy\**" />
    <Compile Remove="Finance\**" />
    <Compile Remove="ROI\**" />
    <Compile Remove="Settings\**" />
    <EmbeddedResource Remove="Energy\**" />
    <EmbeddedResource Remove="Finance\**" />
    <EmbeddedResource Remove="ROI\**" />
    <EmbeddedResource Remove="Settings\**" />
    <None Remove="Energy\**" />
    <None Remove="Finance\**" />
    <None Remove="ROI\**" />
    <None Remove="Settings\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\THMS.Domain\THMS.Domain.csproj" />
  </ItemGroup>

</Project>
