<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>THMS.UI.WinForms</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Properties\Icons\Action.png" />
    <None Remove="Properties\Icons\Currency.png" />
    <None Remove="Properties\Icons\Home.png" />
    <None Remove="Properties\Icons\MoveUp.png" />
    <None Remove="Properties\Icons\Settings.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Properties\Icons\Action.png" />
    <EmbeddedResource Include="Properties\Icons\Currency.png" />
    <EmbeddedResource Include="Properties\Icons\Home.png" />
    <EmbeddedResource Include="Properties\Icons\MoveUp.png" />
    <EmbeddedResource Include="Properties\Icons\Settings.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\THMS.Data\THMS.Data.csproj" />
    <ProjectReference Include="..\THMS.Domain\THMS.Domain.csproj" />
    <ProjectReference Include="..\THMS.Logic\THMS.Logic.csproj" />
    <ProjectReference Include="..\THMS.UI.Common\THMS.UI.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
